### ISSUE TITLE
Comparison with other utils?

### ISSUE THREAD

**Issue by joebowbeer** [jbiskur/nestjs-utils#5]
These utils look very interesting! Are they written up somewhere?

I'd like to see the module factories provided here compared to [createConfigurableDynamicRootModule](https://github.com/golevelup/nestjs/tree/master/packages/modules) from `@golevelup/nestjs-modules`

Also see:
* Article - https://dev.to/nestjs/providing-providers-to-dynamic-nestjs-modules-1i6n
* Demo - https://github.com/koakh/NestJsProvidingProvidersToDynamicNestJSModules

By the way, I added a reference to your `withModule` override to the NestJS [feature request](https://github.com/nestjs/nest/issues/4905).

**Comment by jbiskur** [comment]
I've had plans for a while to write about them in a medium article, but have not had the time yet. Regarding the @golevelup it is very similar. We created this library before I know of the other one tbh :) have looked at it, also used some of his other libraries in other projects, like the discovery lib. Currently, we only have the readme in each lib as a how-to.

**Comment by jbiskur** [comment]
Another difference is that the usage signature can be a bit simpler. 

registerAsync({}) rather than registerAsync({}, MODULE_NAME).

as well as the inclusion of ModuleOptions rather than a const, but that is more useful if you intend to include share a service between multiple modules that use different module options.

**Comment by jbiskur** [comment]
I am closing the issue; please feel free to open a new issue if the answer was not satisfactory
